#!/bin/bash

# autorun
# launches programs at startup

# setting the keyboard map
setxkbmap pl

# run unless there is already an instance
run () {
  if ! pgrep -f "$1" ;
  then
    "$@"&
  fi
}

# restart pipewire
systemctl restart --user pipewire

# compositor
run picom

# wallpaper
$HOME/.fehbg
