#!/bin/bash

# setting the keyboard map
setxkbmap pl

# run unless there is already an instance
run () {
    if ! pgrep -f "$1" ;
    then
        "$@"&
    fi
}

# compositor
run picom

# wallpaper
$HOME/.fehbg

# opening eww widgets on startup
display_count=$(xrandr -q | grep -w 'connected' | wc -l)
if [[ $display_count -gt 1 ]]; then
  $HOME/.cache/yay/eww/target/release/eww open horizontal-bar
  $HOME/.cache/yay/eww/target/release/eww open-many side-workspaces side-clock
else
  $HOME/.cache/yay/eww/target/release/eww open horizontal-bar
fi
