#!/bin/bash

# rotate_display
# rotates display to given position and switches
# eww widgets (assumes main display is rotated)

display=$1
rotation=$2

xrandr --output $1 --rotate $rotation


if [[ $rotation == 'right' ]] || [[ $rotation == 'left' ]]; then
  eww close horizontal-bar
  eww open vertical-bar
else
  eww close vertical-bar
  eww open horizontal-bar
fi
