#!/bin/bash

## run-eww
# Simple utility, called when eww integration is required.
##

eww_path=$HOME/.local/share/eww/target/release/eww

run_eww() {
  display_count=$(xrandr -q | grep -w 'connected' | wc -l)
  if [[ $display_count -gt 1 ]]; then
    # multihead setup
    $eww_path open horizontal-bar
    $eww_path open-many side-workspaces side-clock
  else
    $eww_path open horizontal-bar
  fi
}

run_eww
